# Generated by Django 4.0.4 on 2022-06-02 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tickets.tickets'),
        ),
    ]
