# Generated by Django 4.0.4 on 2022-06-02 02:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('flaw', 'Flaw'), ('improvemente', 'Improvemente'), ('suggestion', 'Suggestion')], max_length=255)),
                ('description', models.TextField()),
                ('test_steps', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('critical', 'Critical')], max_length=255)),
                ('frequency', models.CharField(choices=[('Constact', 'Constact'), ('Periodic', 'Periodic'), ('Irreproducible', 'Irreproducible')], max_length=255)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('irrelevant', 'Irrelevant'), ('admitted', 'Admitted'), ('assignet', 'Assignet'), ('done', 'Done'), ('returned', 'Returned'), ('resolved', 'Resolved')], max_length=255)),
                ('deadline', models.DateField(default='2020-03-15')),
            ],
        ),
    ]
