# Generated by Django 4.0.4 on 2022-06-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_rename_responsibles_tickets_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
